"""1"""
"""mensaje='¡HOLA, BUENAS TARDES FEDERICO!'
print(mensaje)
mensaje='HOLA, BUENAS NOCHES FRANCO!'
print(mensaje)"""
"""2"""
"""ALMACEN='FEDE'
print("Hola",ALMACEN,", ¿te gustaría aprender a programar?")"""
"""3"""
"""num=int(input("ingresa un numero: "))
print(num-(num*15)/100)"""
"""4"""
"""print("INGRESA TRES VALORES PARA VER SU PROMEDIO")
NUM1=int(input("INGRESA EL PRIMER VALOR NUMERICO: "))
NUM2=int(input("INGRESA EL SEGUNDO VALOR NUMERICO: "))
NUM3=int(input("INGRESA EL TERCER VALOR NUMERICO: "))
print((NUM1+NUM2+NUM3)/3)"""
"""5"""
"""print("INGRESE SU NOMBRE DE USUARIO Y SU EDAD")
NOMBRE=input('INGRESE SU NOMBRE Y APELLIDO: ')
EDAD=int(input('INGRESE SU EDAD: '))
CUMPLIRA=(2023-EDAD+100)
print("CUMPLIRA 100 AÑOS EN EL AÑO",CUMPLIRA,)"""
"""6"""
"""PESO=int(input("INGRESE SU PESO EN KG: "))
LIBRAS=(PESO*2,2)
print("SU PESO EN LIBRAS ES",LIBRAS,)"""
"""7"""
"""CEL=int(input("INGRESE SU TEMPERATURA EN GRADOS CELSIUS: "))
TEMFINAL=(CEL*33.8)
print("DE CELSIUS A FAHRENHEIT ES",TEMFINAL,)"""